apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zub3bfa0d-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zub3bfa0d-dotnet-basic-gitops